import "../public/static/css/app.4d2d73d.css";
import "../public/static/css/glider.6f8873f.css";
import "../public/static/css/p.css";
import "../public/static/css/projects.aba1ea5.css";
import "../public/static/css/style.css";
import "../public/static/css/wic4jic.css";
import "../public/static/css/tailwind.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
